Major improvements to the Rule engine and bugfixes for Sales rules
UnionVMS/UVMS-RulesModule-APP pull request #298
Opened 2018-05-04 07:50 UTC by stainii

**Major improvements** 
* Fix that, when something is already on the Rules queue before Rules starts up, the module did not deploy anymore
* When checking MDR lists, the MDR list's validity period is now taken into account **for Sales rules. @COM, please do the same for Activity rules**.
* Speed improvement: we've removed some unnecessary write locks on several singletons. Also, we've made it possible to validate both incoming as outgoing Sales messages at the same time, speeding up the processing of Sales messages up to a factor 5. 
 

**Bugfixes of Sales rules**
* Added code for SALE-L01-00-0130. Because this rule has not been thoroughly tested yet, and needs a change in the Asset-model, we've put this code in comments for now. We hope to do the necessary actions as soon as possible to uncomment the code.
* Fixed SALE-L01-00-0082: it was still using a hardcoded list of values, instead of MDR
* Enabled SALE-L01-00-0452
* Fix ArrayOutOfBoundsException for SALE-L01-00-0036
* Fix sending Sales reports to FLUX

2018-05-04 09:58 UTC, gregoryrinaldi requested changes

2018-05-04 09:58 UTC, gregoryrinaldi commented on message/src/main/java/eu/europa/ec/fisheries/uvms/rules/message/consumer/bean/RulesEventMessageConsumerBean.java
> +        @ActivationConfigProperty(propertyName = "messageSelector", propertyValue = "messageSelector IS NULL")
@stainii 
Can you explain which messages will be picked up by this MDB?
Why we have the same events here and in the RulesDefaultSelectorEventConsumerBean?
for ex: SetFLUXFAReportMessageReceivedEvent

2018-05-04 09:58 UTC, gregoryrinaldi commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/helper/AssetServiceBeanHelper.java
> +//    @EJB
Why committing commented code?
Aren't we supposed to have a full working version of  the code before committing to dev?

2018-05-04 09:58 UTC, gregoryrinaldi commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/AssetServiceBean.java
> +//        try {
Why committing commented code?
Aren't we supposed to have a full working version of the code before committing to dev?

Why not use the extravaluemap for the assets aswell and call it only once and not calling another modules during validation?

2018-05-04 09:58 UTC, gregoryrinaldi commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/business/AbstractFact.java
> +    protected DateTime creationDateOfMessage;
Is this really needed in al the facts?
Cause usually you map it to the particular fact that uses it...

2018-05-04 10:05 UTC, stainii commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/helper/AssetServiceBeanHelper.java
> +//    @EJB
Ideally, yes. We are, however, in quite a pickle because of Assets. Our changes to that module are not ready, and will not be for a few weeks. This situation will be rectified as soon as possible, it's very high on our todo list.

See the description of this pull request:
"Added code for SALE-L01-00-0130. Because this rule has not been thoroughly tested yet, and needs a change in the Asset-model, we've put this code in comments for now. We hope to do the necessary actions as soon as possible to uncomment the code."

2018-05-04 10:06 UTC, stainii commented on message/src/main/java/eu/europa/ec/fisheries/uvms/rules/message/consumer/bean/RulesEventMessageConsumerBean.java
> +        @ActivationConfigProperty(propertyName = "messageSelector", propertyValue = "messageSelector IS NULL")
This was not clear for Andreas as well. I'll push a new commit soon that will make things more clear.

2018-05-04 10:07 UTC, stainii commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/business/AbstractFact.java
> +    protected DateTime creationDateOfMessage;
Every fact that contains something that should be checked in MDR, will use it. That's very close to almost every fact.

2018-05-04 10:09 UTC, stainii commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/AssetServiceBean.java
> +//        try {
We're not using the extravaluemap because that means we would cache every possible asset in the fleet registry, in Rules. The extravaluemap should only be used for small data sets.

2018-05-04 11:31 UTC, stainii commented
Here you go. I've removed the duplicated code, and added comments in several places to explain what the purpose is of every MDB.

2018-05-04 14:38 UTC, stainii commented on message/src/main/java/eu/europa/ec/fisheries/uvms/rules/message/consumer/bean/RulesEventMessageConsumerBean.java
> +        @ActivationConfigProperty(propertyName = "messageSelector", propertyValue = "messageSelector IS NULL")
Please have a look at https://github.com/UnionVMS/UVMS-RulesModule-APP/pull/298/commits/423959491a7858bbde732029ad61d1eaecfb2ebf

2018-05-04 17:02 UTC, ankovi commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/AssetServiceBean.java
> +//        try {
I don't know which is your use case, but, in case of FaReports we actually take from Assets only particular ones (cause in the message we recieve CFR, FLAG_STATE, IRCS or a combination.., I guess you do too..)... You never need to fetch all the Assets at once in Rules..
You can do the same and your validation would be faster (if you call assets more than once during validation)..

2018-05-07 10:51 UTC, stainii commented on service/src/main/java/eu/europa/ec/fisheries/uvms/rules/service/bean/sales/AssetServiceBean.java
> +//        try {
In our case, it would be a single call. We can have a look at how your team did it with the extraValuesMap.
But anyway, this is unfinished, commented code, so let's not block the pull request because of this.

2018-05-07 13:50 UTC, gregoryrinaldi approved these changes
Tested some rules, tested saving af activity and everything seems to be working like before so for me it is ok

2018-05-07 14:16 UTC, ebrygg approved these changes
ok

2018-05-08 05:24 UTC, merged